/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bistel.a3.portal.spark.common;

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SparkResponseCode implements org.apache.thrift.TEnum {
  SUCCESS(0),
  FAIL(1);

  private final int value;

  private SparkResponseCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SparkResponseCode findByValue(int value) { 
    switch (value) {
      case 0:
        return SUCCESS;
      case 1:
        return FAIL;
      default:
        return null;
    }
  }
}
