/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bistel.a3.portal.thrift.client.iface;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2015-11-30")
public class SparkPdMRequest implements org.apache.thrift.TBase<SparkPdMRequest, SparkPdMRequest._Fields>, java.io.Serializable, Cloneable, Comparable<SparkPdMRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SparkRankRequest");

  private static final org.apache.thrift.protocol.TField HOST_FIELD_DESC = new org.apache.thrift.protocol.TField("host", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PORT_FIELD_DESC = new org.apache.thrift.protocol.TField("port", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField FUNC_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("funcName", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField REQUEST_CONTENT_FIELD_DESC = new org.apache.thrift.protocol.TField("requestContent", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SparkRankRequestStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SparkRankRequestTupleSchemeFactory());
  }

  public String host; // required
  public int port; // required
  public String funcName; // required
  public String requestContent; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    HOST((short)1, "host"),
    PORT((short)2, "port"),
    FUNC_NAME((short)3, "funcName"),
    REQUEST_CONTENT((short)4, "requestContent");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // HOST
          return HOST;
        case 2: // PORT
          return PORT;
        case 3: // FUNC_NAME
          return FUNC_NAME;
        case 4: // REQUEST_CONTENT
          return REQUEST_CONTENT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PORT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.HOST, new org.apache.thrift.meta_data.FieldMetaData("host", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PORT, new org.apache.thrift.meta_data.FieldMetaData("port", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FUNC_NAME, new org.apache.thrift.meta_data.FieldMetaData("funcName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REQUEST_CONTENT, new org.apache.thrift.meta_data.FieldMetaData("requestContent", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SparkPdMRequest.class, metaDataMap);
  }

  public SparkPdMRequest() {
  }

  public SparkPdMRequest(
    String host,
    int port,
    String funcName,
    String requestContent)
  {
    this();
    this.host = host;
    this.port = port;
    setPortIsSet(true);
    this.funcName = funcName;
    this.requestContent = requestContent;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SparkPdMRequest(SparkPdMRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetHost()) {
      this.host = other.host;
    }
    this.port = other.port;
    if (other.isSetFuncName()) {
      this.funcName = other.funcName;
    }
    if (other.isSetRequestContent()) {
      this.requestContent = other.requestContent;
    }
  }

  public SparkPdMRequest deepCopy() {
    return new SparkPdMRequest(this);
  }

  @Override
  public void clear() {
    this.host = null;
    setPortIsSet(false);
    this.port = 0;
    this.funcName = null;
    this.requestContent = null;
  }

  public String getHost() {
    return this.host;
  }

  public SparkPdMRequest setHost(String host) {
    this.host = host;
    return this;
  }

  public void unsetHost() {
    this.host = null;
  }

  /** Returns true if field host is set (has been assigned a value) and false otherwise */
  public boolean isSetHost() {
    return this.host != null;
  }

  public void setHostIsSet(boolean value) {
    if (!value) {
      this.host = null;
    }
  }

  public int getPort() {
    return this.port;
  }

  public SparkPdMRequest setPort(int port) {
    this.port = port;
    setPortIsSet(true);
    return this;
  }

  public void unsetPort() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PORT_ISSET_ID);
  }

  /** Returns true if field port is set (has been assigned a value) and false otherwise */
  public boolean isSetPort() {
    return EncodingUtils.testBit(__isset_bitfield, __PORT_ISSET_ID);
  }

  public void setPortIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PORT_ISSET_ID, value);
  }

  public String getFuncName() {
    return this.funcName;
  }

  public SparkPdMRequest setFuncName(String funcName) {
    this.funcName = funcName;
    return this;
  }

  public void unsetFuncName() {
    this.funcName = null;
  }

  /** Returns true if field funcName is set (has been assigned a value) and false otherwise */
  public boolean isSetFuncName() {
    return this.funcName != null;
  }

  public void setFuncNameIsSet(boolean value) {
    if (!value) {
      this.funcName = null;
    }
  }

  public String getRequestContent() {
    return this.requestContent;
  }

  public SparkPdMRequest setRequestContent(String requestContent) {
    this.requestContent = requestContent;
    return this;
  }

  public void unsetRequestContent() {
    this.requestContent = null;
  }

  /** Returns true if field requestContent is set (has been assigned a value) and false otherwise */
  public boolean isSetRequestContent() {
    return this.requestContent != null;
  }

  public void setRequestContentIsSet(boolean value) {
    if (!value) {
      this.requestContent = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case HOST:
      if (value == null) {
        unsetHost();
      } else {
        setHost((String)value);
      }
      break;

    case PORT:
      if (value == null) {
        unsetPort();
      } else {
        setPort((Integer)value);
      }
      break;

    case FUNC_NAME:
      if (value == null) {
        unsetFuncName();
      } else {
        setFuncName((String)value);
      }
      break;

    case REQUEST_CONTENT:
      if (value == null) {
        unsetRequestContent();
      } else {
        setRequestContent((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case HOST:
      return getHost();

    case PORT:
      return getPort();

    case FUNC_NAME:
      return getFuncName();

    case REQUEST_CONTENT:
      return getRequestContent();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case HOST:
      return isSetHost();
    case PORT:
      return isSetPort();
    case FUNC_NAME:
      return isSetFuncName();
    case REQUEST_CONTENT:
      return isSetRequestContent();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SparkPdMRequest)
      return this.equals((SparkPdMRequest)that);
    return false;
  }

  public boolean equals(SparkPdMRequest that) {
    if (that == null)
      return false;

    boolean this_present_host = true && this.isSetHost();
    boolean that_present_host = true && that.isSetHost();
    if (this_present_host || that_present_host) {
      if (!(this_present_host && that_present_host))
        return false;
      if (!this.host.equals(that.host))
        return false;
    }

    boolean this_present_port = true;
    boolean that_present_port = true;
    if (this_present_port || that_present_port) {
      if (!(this_present_port && that_present_port))
        return false;
      if (this.port != that.port)
        return false;
    }

    boolean this_present_funcName = true && this.isSetFuncName();
    boolean that_present_funcName = true && that.isSetFuncName();
    if (this_present_funcName || that_present_funcName) {
      if (!(this_present_funcName && that_present_funcName))
        return false;
      if (!this.funcName.equals(that.funcName))
        return false;
    }

    boolean this_present_requestContent = true && this.isSetRequestContent();
    boolean that_present_requestContent = true && that.isSetRequestContent();
    if (this_present_requestContent || that_present_requestContent) {
      if (!(this_present_requestContent && that_present_requestContent))
        return false;
      if (!this.requestContent.equals(that.requestContent))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_host = true && (isSetHost());
    list.add(present_host);
    if (present_host)
      list.add(host);

    boolean present_port = true;
    list.add(present_port);
    if (present_port)
      list.add(port);

    boolean present_funcName = true && (isSetFuncName());
    list.add(present_funcName);
    if (present_funcName)
      list.add(funcName);

    boolean present_requestContent = true && (isSetRequestContent());
    list.add(present_requestContent);
    if (present_requestContent)
      list.add(requestContent);

    return list.hashCode();
  }

  @Override
  public int compareTo(SparkPdMRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetHost()).compareTo(other.isSetHost());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHost()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.host, other.host);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPort()).compareTo(other.isSetPort());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPort()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.port, other.port);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFuncName()).compareTo(other.isSetFuncName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFuncName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.funcName, other.funcName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRequestContent()).compareTo(other.isSetRequestContent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRequestContent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.requestContent, other.requestContent);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SparkRankRequest(");
    boolean first = true;

    sb.append("host:");
    if (this.host == null) {
      sb.append("null");
    } else {
      sb.append(this.host);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("port:");
    sb.append(this.port);
    first = false;
    if (!first) sb.append(", ");
    sb.append("funcName:");
    if (this.funcName == null) {
      sb.append("null");
    } else {
      sb.append(this.funcName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("requestContent:");
    if (this.requestContent == null) {
      sb.append("null");
    } else {
      sb.append(this.requestContent);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SparkRankRequestStandardSchemeFactory implements SchemeFactory {
    public SparkRankRequestStandardScheme getScheme() {
      return new SparkRankRequestStandardScheme();
    }
  }

  private static class SparkRankRequestStandardScheme extends StandardScheme<SparkPdMRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SparkPdMRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // HOST
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.host = iprot.readString();
              struct.setHostIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PORT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.port = iprot.readI32();
              struct.setPortIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // FUNC_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.funcName = iprot.readString();
              struct.setFuncNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // REQUEST_CONTENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.requestContent = iprot.readString();
              struct.setRequestContentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SparkPdMRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.host != null) {
        oprot.writeFieldBegin(HOST_FIELD_DESC);
        oprot.writeString(struct.host);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PORT_FIELD_DESC);
      oprot.writeI32(struct.port);
      oprot.writeFieldEnd();
      if (struct.funcName != null) {
        oprot.writeFieldBegin(FUNC_NAME_FIELD_DESC);
        oprot.writeString(struct.funcName);
        oprot.writeFieldEnd();
      }
      if (struct.requestContent != null) {
        oprot.writeFieldBegin(REQUEST_CONTENT_FIELD_DESC);
        oprot.writeString(struct.requestContent);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SparkRankRequestTupleSchemeFactory implements SchemeFactory {
    public SparkRankRequestTupleScheme getScheme() {
      return new SparkRankRequestTupleScheme();
    }
  }

  private static class SparkRankRequestTupleScheme extends TupleScheme<SparkPdMRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SparkPdMRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetHost()) {
        optionals.set(0);
      }
      if (struct.isSetPort()) {
        optionals.set(1);
      }
      if (struct.isSetFuncName()) {
        optionals.set(2);
      }
      if (struct.isSetRequestContent()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetHost()) {
        oprot.writeString(struct.host);
      }
      if (struct.isSetPort()) {
        oprot.writeI32(struct.port);
      }
      if (struct.isSetFuncName()) {
        oprot.writeString(struct.funcName);
      }
      if (struct.isSetRequestContent()) {
        oprot.writeString(struct.requestContent);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SparkPdMRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.host = iprot.readString();
        struct.setHostIsSet(true);
      }
      if (incoming.get(1)) {
        struct.port = iprot.readI32();
        struct.setPortIsSet(true);
      }
      if (incoming.get(2)) {
        struct.funcName = iprot.readString();
        struct.setFuncNameIsSet(true);
      }
      if (incoming.get(3)) {
        struct.requestContent = iprot.readString();
        struct.setRequestContentIsSet(true);
      }
    }
  }

}

