/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bistel.a3.portal.thrift.client.iface;

import java.util.ArrayList;
import java.util.BitSet;
import java.util.Collections;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.Generated;

import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2015-11-18")
public class SparkResponse implements org.apache.thrift.TBase<SparkResponse, SparkResponse._Fields>, java.io.Serializable, Cloneable, Comparable<SparkResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SparkResponse");

  private static final org.apache.thrift.protocol.TField CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("code", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField RESPONSE_CONTENT_FIELD_DESC = new org.apache.thrift.protocol.TField("responseContent", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SparkResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SparkResponseTupleSchemeFactory());
  }

  /**
   * 
   * @see SparkResponseCode
   */
  public SparkResponseCode code; // required
  public String responseContent; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see SparkResponseCode
     */
    CODE((short)1, "code"),
    RESPONSE_CONTENT((short)2, "responseContent");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CODE
          return CODE;
        case 2: // RESPONSE_CONTENT
          return RESPONSE_CONTENT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CODE, new org.apache.thrift.meta_data.FieldMetaData("code", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, SparkResponseCode.class)));
    tmpMap.put(_Fields.RESPONSE_CONTENT, new org.apache.thrift.meta_data.FieldMetaData("responseContent", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SparkResponse.class, metaDataMap);
  }

  public SparkResponse() {
  }

  public SparkResponse(
    SparkResponseCode code,
    String responseContent)
  {
    this();
    this.code = code;
    this.responseContent = responseContent;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SparkResponse(SparkResponse other) {
    if (other.isSetCode()) {
      this.code = other.code;
    }
    if (other.isSetResponseContent()) {
      this.responseContent = other.responseContent;
    }
  }

  public SparkResponse deepCopy() {
    return new SparkResponse(this);
  }

  @Override
  public void clear() {
    this.code = null;
    this.responseContent = null;
  }

  /**
   * 
   * @see SparkResponseCode
   */
  public SparkResponseCode getCode() {
    return this.code;
  }

  /**
   * 
   * @see SparkResponseCode
   */
  public SparkResponse setCode(SparkResponseCode code) {
    this.code = code;
    return this;
  }

  public void unsetCode() {
    this.code = null;
  }

  /** Returns true if field code is set (has been assigned a value) and false otherwise */
  public boolean isSetCode() {
    return this.code != null;
  }

  public void setCodeIsSet(boolean value) {
    if (!value) {
      this.code = null;
    }
  }

  public String getResponseContent() {
    return this.responseContent;
  }

  public SparkResponse setResponseContent(String responseContent) {
    this.responseContent = responseContent;
    return this;
  }

  public void unsetResponseContent() {
    this.responseContent = null;
  }

  /** Returns true if field responseContent is set (has been assigned a value) and false otherwise */
  public boolean isSetResponseContent() {
    return this.responseContent != null;
  }

  public void setResponseContentIsSet(boolean value) {
    if (!value) {
      this.responseContent = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CODE:
      if (value == null) {
        unsetCode();
      } else {
        setCode((SparkResponseCode)value);
      }
      break;

    case RESPONSE_CONTENT:
      if (value == null) {
        unsetResponseContent();
      } else {
        setResponseContent((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CODE:
      return getCode();

    case RESPONSE_CONTENT:
      return getResponseContent();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CODE:
      return isSetCode();
    case RESPONSE_CONTENT:
      return isSetResponseContent();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SparkResponse)
      return this.equals((SparkResponse)that);
    return false;
  }

  public boolean equals(SparkResponse that) {
    if (that == null)
      return false;

    boolean this_present_code = true && this.isSetCode();
    boolean that_present_code = true && that.isSetCode();
    if (this_present_code || that_present_code) {
      if (!(this_present_code && that_present_code))
        return false;
      if (!this.code.equals(that.code))
        return false;
    }

    boolean this_present_responseContent = true && this.isSetResponseContent();
    boolean that_present_responseContent = true && that.isSetResponseContent();
    if (this_present_responseContent || that_present_responseContent) {
      if (!(this_present_responseContent && that_present_responseContent))
        return false;
      if (!this.responseContent.equals(that.responseContent))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_code = true && (isSetCode());
    list.add(present_code);
    if (present_code)
      list.add(code.getValue());

    boolean present_responseContent = true && (isSetResponseContent());
    list.add(present_responseContent);
    if (present_responseContent)
      list.add(responseContent);

    return list.hashCode();
  }

  @Override
  public int compareTo(SparkResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetCode()).compareTo(other.isSetCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.code, other.code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetResponseContent()).compareTo(other.isSetResponseContent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResponseContent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.responseContent, other.responseContent);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SparkResponse(");
    boolean first = true;

    sb.append("code:");
    if (this.code == null) {
      sb.append("null");
    } else {
      sb.append(this.code);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("responseContent:");
    if (this.responseContent == null) {
      sb.append("null");
    } else {
      sb.append(this.responseContent);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SparkResponseStandardSchemeFactory implements SchemeFactory {
    public SparkResponseStandardScheme getScheme() {
      return new SparkResponseStandardScheme();
    }
  }

  private static class SparkResponseStandardScheme extends StandardScheme<SparkResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SparkResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.code = com.bistel.a3.portal.thrift.client.iface.SparkResponseCode.findByValue(iprot.readI32());
              struct.setCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RESPONSE_CONTENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.responseContent = iprot.readString();
              struct.setResponseContentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SparkResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.code != null) {
        oprot.writeFieldBegin(CODE_FIELD_DESC);
        oprot.writeI32(struct.code.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.responseContent != null) {
        oprot.writeFieldBegin(RESPONSE_CONTENT_FIELD_DESC);
        oprot.writeString(struct.responseContent);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SparkResponseTupleSchemeFactory implements SchemeFactory {
    public SparkResponseTupleScheme getScheme() {
      return new SparkResponseTupleScheme();
    }
  }

  private static class SparkResponseTupleScheme extends TupleScheme<SparkResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SparkResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetCode()) {
        optionals.set(0);
      }
      if (struct.isSetResponseContent()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetCode()) {
        oprot.writeI32(struct.code.getValue());
      }
      if (struct.isSetResponseContent()) {
        oprot.writeString(struct.responseContent);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SparkResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.code = com.bistel.a3.portal.thrift.client.iface.SparkResponseCode.findByValue(iprot.readI32());
        struct.setCodeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.responseContent = iprot.readString();
        struct.setResponseContentIsSet(true);
      }
    }
  }

}

