/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bistel.a3.portal.thrift.client.iface;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2015-11-24")
public class SparkRequest implements org.apache.thrift.TBase<SparkRequest, SparkRequest._Fields>, java.io.Serializable, Cloneable, Comparable<SparkRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SparkRequest");

  private static final org.apache.thrift.protocol.TField HOST_FIELD_DESC = new org.apache.thrift.protocol.TField("host", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PORT_FIELD_DESC = new org.apache.thrift.protocol.TField("port", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField SUMMARY_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("summaryType", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField ACTIVITY_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("activityId", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField REQUEST_CONTENT_FIELD_DESC = new org.apache.thrift.protocol.TField("requestContent", org.apache.thrift.protocol.TType.STRING, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SparkRequestStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SparkRequestTupleSchemeFactory());
  }

  public String host; // required
  public int port; // required
  public String summaryType; // required
  public String activityId; // required
  public String requestContent; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    HOST((short)1, "host"),
    PORT((short)2, "port"),
    SUMMARY_TYPE((short)3, "summaryType"),
    ACTIVITY_ID((short)4, "activityId"),
    REQUEST_CONTENT((short)5, "requestContent");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // HOST
          return HOST;
        case 2: // PORT
          return PORT;
        case 3: // SUMMARY_TYPE
          return SUMMARY_TYPE;
        case 4: // ACTIVITY_ID
          return ACTIVITY_ID;
        case 5: // REQUEST_CONTENT
          return REQUEST_CONTENT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PORT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.HOST, new org.apache.thrift.meta_data.FieldMetaData("host", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PORT, new org.apache.thrift.meta_data.FieldMetaData("port", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SUMMARY_TYPE, new org.apache.thrift.meta_data.FieldMetaData("summaryType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ACTIVITY_ID, new org.apache.thrift.meta_data.FieldMetaData("activityId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REQUEST_CONTENT, new org.apache.thrift.meta_data.FieldMetaData("requestContent", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SparkRequest.class, metaDataMap);
  }

  public SparkRequest() {
  }

  public SparkRequest(
    String host,
    int port,
    String summaryType,
    String activityId,
    String requestContent)
  {
    this();
    this.host = host;
    this.port = port;
    setPortIsSet(true);
    this.summaryType = summaryType;
    this.activityId = activityId;
    this.requestContent = requestContent;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SparkRequest(SparkRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetHost()) {
      this.host = other.host;
    }
    this.port = other.port;
    if (other.isSetSummaryType()) {
      this.summaryType = other.summaryType;
    }
    if (other.isSetActivityId()) {
      this.activityId = other.activityId;
    }
    if (other.isSetRequestContent()) {
      this.requestContent = other.requestContent;
    }
  }

  public SparkRequest deepCopy() {
    return new SparkRequest(this);
  }

  @Override
  public void clear() {
    this.host = null;
    setPortIsSet(false);
    this.port = 0;
    this.summaryType = null;
    this.activityId = null;
    this.requestContent = null;
  }

  public String getHost() {
    return this.host;
  }

  public SparkRequest setHost(String host) {
    this.host = host;
    return this;
  }

  public void unsetHost() {
    this.host = null;
  }

  /** Returns true if field host is set (has been assigned a value) and false otherwise */
  public boolean isSetHost() {
    return this.host != null;
  }

  public void setHostIsSet(boolean value) {
    if (!value) {
      this.host = null;
    }
  }

  public int getPort() {
    return this.port;
  }

  public SparkRequest setPort(int port) {
    this.port = port;
    setPortIsSet(true);
    return this;
  }

  public void unsetPort() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PORT_ISSET_ID);
  }

  /** Returns true if field port is set (has been assigned a value) and false otherwise */
  public boolean isSetPort() {
    return EncodingUtils.testBit(__isset_bitfield, __PORT_ISSET_ID);
  }

  public void setPortIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PORT_ISSET_ID, value);
  }

  public String getSummaryType() {
    return this.summaryType;
  }

  public SparkRequest setSummaryType(String summaryType) {
    this.summaryType = summaryType;
    return this;
  }

  public void unsetSummaryType() {
    this.summaryType = null;
  }

  /** Returns true if field summaryType is set (has been assigned a value) and false otherwise */
  public boolean isSetSummaryType() {
    return this.summaryType != null;
  }

  public void setSummaryTypeIsSet(boolean value) {
    if (!value) {
      this.summaryType = null;
    }
  }

  public String getActivityId() {
    return this.activityId;
  }

  public SparkRequest setActivityId(String activityId) {
    this.activityId = activityId;
    return this;
  }

  public void unsetActivityId() {
    this.activityId = null;
  }

  /** Returns true if field activityId is set (has been assigned a value) and false otherwise */
  public boolean isSetActivityId() {
    return this.activityId != null;
  }

  public void setActivityIdIsSet(boolean value) {
    if (!value) {
      this.activityId = null;
    }
  }

  public String getRequestContent() {
    return this.requestContent;
  }

  public SparkRequest setRequestContent(String requestContent) {
    this.requestContent = requestContent;
    return this;
  }

  public void unsetRequestContent() {
    this.requestContent = null;
  }

  /** Returns true if field requestContent is set (has been assigned a value) and false otherwise */
  public boolean isSetRequestContent() {
    return this.requestContent != null;
  }

  public void setRequestContentIsSet(boolean value) {
    if (!value) {
      this.requestContent = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case HOST:
      if (value == null) {
        unsetHost();
      } else {
        setHost((String)value);
      }
      break;

    case PORT:
      if (value == null) {
        unsetPort();
      } else {
        setPort((Integer)value);
      }
      break;

    case SUMMARY_TYPE:
      if (value == null) {
        unsetSummaryType();
      } else {
        setSummaryType((String)value);
      }
      break;

    case ACTIVITY_ID:
      if (value == null) {
        unsetActivityId();
      } else {
        setActivityId((String)value);
      }
      break;

    case REQUEST_CONTENT:
      if (value == null) {
        unsetRequestContent();
      } else {
        setRequestContent((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case HOST:
      return getHost();

    case PORT:
      return getPort();

    case SUMMARY_TYPE:
      return getSummaryType();

    case ACTIVITY_ID:
      return getActivityId();

    case REQUEST_CONTENT:
      return getRequestContent();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case HOST:
      return isSetHost();
    case PORT:
      return isSetPort();
    case SUMMARY_TYPE:
      return isSetSummaryType();
    case ACTIVITY_ID:
      return isSetActivityId();
    case REQUEST_CONTENT:
      return isSetRequestContent();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SparkRequest)
      return this.equals((SparkRequest)that);
    return false;
  }

  public boolean equals(SparkRequest that) {
    if (that == null)
      return false;

    boolean this_present_host = true && this.isSetHost();
    boolean that_present_host = true && that.isSetHost();
    if (this_present_host || that_present_host) {
      if (!(this_present_host && that_present_host))
        return false;
      if (!this.host.equals(that.host))
        return false;
    }

    boolean this_present_port = true;
    boolean that_present_port = true;
    if (this_present_port || that_present_port) {
      if (!(this_present_port && that_present_port))
        return false;
      if (this.port != that.port)
        return false;
    }

    boolean this_present_summaryType = true && this.isSetSummaryType();
    boolean that_present_summaryType = true && that.isSetSummaryType();
    if (this_present_summaryType || that_present_summaryType) {
      if (!(this_present_summaryType && that_present_summaryType))
        return false;
      if (!this.summaryType.equals(that.summaryType))
        return false;
    }

    boolean this_present_activityId = true && this.isSetActivityId();
    boolean that_present_activityId = true && that.isSetActivityId();
    if (this_present_activityId || that_present_activityId) {
      if (!(this_present_activityId && that_present_activityId))
        return false;
      if (!this.activityId.equals(that.activityId))
        return false;
    }

    boolean this_present_requestContent = true && this.isSetRequestContent();
    boolean that_present_requestContent = true && that.isSetRequestContent();
    if (this_present_requestContent || that_present_requestContent) {
      if (!(this_present_requestContent && that_present_requestContent))
        return false;
      if (!this.requestContent.equals(that.requestContent))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_host = true && (isSetHost());
    list.add(present_host);
    if (present_host)
      list.add(host);

    boolean present_port = true;
    list.add(present_port);
    if (present_port)
      list.add(port);

    boolean present_summaryType = true && (isSetSummaryType());
    list.add(present_summaryType);
    if (present_summaryType)
      list.add(summaryType);

    boolean present_activityId = true && (isSetActivityId());
    list.add(present_activityId);
    if (present_activityId)
      list.add(activityId);

    boolean present_requestContent = true && (isSetRequestContent());
    list.add(present_requestContent);
    if (present_requestContent)
      list.add(requestContent);

    return list.hashCode();
  }

  @Override
  public int compareTo(SparkRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetHost()).compareTo(other.isSetHost());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHost()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.host, other.host);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPort()).compareTo(other.isSetPort());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPort()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.port, other.port);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSummaryType()).compareTo(other.isSetSummaryType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSummaryType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.summaryType, other.summaryType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetActivityId()).compareTo(other.isSetActivityId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetActivityId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.activityId, other.activityId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRequestContent()).compareTo(other.isSetRequestContent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRequestContent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.requestContent, other.requestContent);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SparkRequest(");
    boolean first = true;

    sb.append("host:");
    if (this.host == null) {
      sb.append("null");
    } else {
      sb.append(this.host);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("port:");
    sb.append(this.port);
    first = false;
    if (!first) sb.append(", ");
    sb.append("summaryType:");
    if (this.summaryType == null) {
      sb.append("null");
    } else {
      sb.append(this.summaryType);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("activityId:");
    if (this.activityId == null) {
      sb.append("null");
    } else {
      sb.append(this.activityId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("requestContent:");
    if (this.requestContent == null) {
      sb.append("null");
    } else {
      sb.append(this.requestContent);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SparkRequestStandardSchemeFactory implements SchemeFactory {
    public SparkRequestStandardScheme getScheme() {
      return new SparkRequestStandardScheme();
    }
  }

  private static class SparkRequestStandardScheme extends StandardScheme<SparkRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SparkRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // HOST
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.host = iprot.readString();
              struct.setHostIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PORT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.port = iprot.readI32();
              struct.setPortIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SUMMARY_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.summaryType = iprot.readString();
              struct.setSummaryTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ACTIVITY_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.activityId = iprot.readString();
              struct.setActivityIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // REQUEST_CONTENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.requestContent = iprot.readString();
              struct.setRequestContentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SparkRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.host != null) {
        oprot.writeFieldBegin(HOST_FIELD_DESC);
        oprot.writeString(struct.host);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PORT_FIELD_DESC);
      oprot.writeI32(struct.port);
      oprot.writeFieldEnd();
      if (struct.summaryType != null) {
        oprot.writeFieldBegin(SUMMARY_TYPE_FIELD_DESC);
        oprot.writeString(struct.summaryType);
        oprot.writeFieldEnd();
      }
      if (struct.activityId != null) {
        oprot.writeFieldBegin(ACTIVITY_ID_FIELD_DESC);
        oprot.writeString(struct.activityId);
        oprot.writeFieldEnd();
      }
      if (struct.requestContent != null) {
        oprot.writeFieldBegin(REQUEST_CONTENT_FIELD_DESC);
        oprot.writeString(struct.requestContent);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SparkRequestTupleSchemeFactory implements SchemeFactory {
    public SparkRequestTupleScheme getScheme() {
      return new SparkRequestTupleScheme();
    }
  }

  private static class SparkRequestTupleScheme extends TupleScheme<SparkRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SparkRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetHost()) {
        optionals.set(0);
      }
      if (struct.isSetPort()) {
        optionals.set(1);
      }
      if (struct.isSetSummaryType()) {
        optionals.set(2);
      }
      if (struct.isSetActivityId()) {
        optionals.set(3);
      }
      if (struct.isSetRequestContent()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetHost()) {
        oprot.writeString(struct.host);
      }
      if (struct.isSetPort()) {
        oprot.writeI32(struct.port);
      }
      if (struct.isSetSummaryType()) {
        oprot.writeString(struct.summaryType);
      }
      if (struct.isSetActivityId()) {
        oprot.writeString(struct.activityId);
      }
      if (struct.isSetRequestContent()) {
        oprot.writeString(struct.requestContent);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SparkRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.host = iprot.readString();
        struct.setHostIsSet(true);
      }
      if (incoming.get(1)) {
        struct.port = iprot.readI32();
        struct.setPortIsSet(true);
      }
      if (incoming.get(2)) {
        struct.summaryType = iprot.readString();
        struct.setSummaryTypeIsSet(true);
      }
      if (incoming.get(3)) {
        struct.activityId = iprot.readString();
        struct.setActivityIdIsSet(true);
      }
      if (incoming.get(4)) {
        struct.requestContent = iprot.readString();
        struct.setRequestContentIsSet(true);
      }
    }
  }

}

